// Package upload validates and normalises user-supplied files before they are
// written to disk.
//
// Uploaded files are served back from the application's own origin, so a file that
// a browser is willing to treat as a document rather than an image becomes script
// execution in the application's security context — able to read the auth state the
// SPA keeps in localStorage. Extension checks alone do not prevent this: a caller
// controls the extension, the declared Content-Type and the bytes independently.
//
// The defence here is to accept only formats the server can fully decode, prove
// each upload really is one of them by decoding it, and then re-encode it from the
// decoded pixels. Re-encoding is what makes a polyglot harmless: whatever markup,
// script or trailing payload the original file carried does not survive being
// rebuilt from an image.Image.
package upload

import (
	"bytes"
	"errors"
	"fmt"
	"image"
	"image/gif"
	"image/jpeg"
	"image/png"
	"io"
	"mime/multipart"
	"strings"

	"github.com/google/uuid"
)

// Validation failures. Callers map these to HTTP status codes.
var (
	ErrEmptyFile     = errors.New("file is empty")
	ErrTooLarge      = errors.New("file is too large")
	ErrNotAnImage    = errors.New("file is not a readable image")
	ErrFormatBlocked = errors.New("image format is not allowed")
	ErrTooManyPixels = errors.New("image dimensions are too large")
)

// maxPixels caps the decoded pixel count. A few kilobytes of highly compressed PNG
// can describe a canvas of hundreds of megapixels, and decoding it would allocate
// gigabytes: a decompression bomb. The limit sits well above any legitimate photo
// (50MP is larger than current full-frame cameras produce) while keeping the worst
// case allocation bounded at roughly 200MB.
const maxPixels = 50_000_000

// Format describes an accepted image format.
type Format struct {
	// Name is the identifier reported by image.DecodeConfig.
	Name string
	// Ext is the canonical file extension, without a leading dot.
	Ext string
	// ContentType is the exact Content-Type the file is later served with. It is
	// fixed per format and never derived from the request or the filename.
	ContentType string
}

// supportedFormats is deliberately restricted to raster formats the standard
// library can both decode and re-encode.
//
// SVG is absent by design and must not be added: it is an XML document that can
// carry <script> and event handlers, browsers execute it when it is navigated to
// directly, and "sanitising" it means maintaining an XML allowlist against a
// constantly moving target. WebP is absent because the standard library cannot
// encode it, so an upload could not be re-encoded and would have to be trusted
// as-is.
var supportedFormats = map[string]Format{
	"jpeg": {Name: "jpeg", Ext: "jpg", ContentType: "image/jpeg"},
	"png":  {Name: "png", Ext: "png", ContentType: "image/png"},
	"gif":  {Name: "gif", Ext: "gif", ContentType: "image/gif"},
}

// extAliases maps the extensions a caller might supply onto a format name.
var extAliases = map[string]string{
	"jpg":  "jpeg",
	"jpeg": "jpeg",
	"png":  "png",
	"gif":  "gif",
}

// Options controls validation.
type Options struct {
	// MaxBytes is the largest accepted upload. Values below 1 disable the limit.
	MaxBytes int64
	// AllowedTypes is the operator's configured extension allowlist
	// (UPLOAD_ALLOWED_TYPES). It is intersected with supportedFormats, so listing a
	// document type there never makes it acceptable to an image endpoint. An empty
	// slice means "no operator restriction" and every supported image format is
	// accepted.
	AllowedTypes []string
}

// allows reports whether the operator's configuration permits this format.
func (o Options) allows(f Format) bool {
	if len(o.AllowedTypes) == 0 {
		return true
	}
	for _, t := range o.AllowedTypes {
		t = strings.ToLower(strings.TrimSpace(strings.TrimPrefix(t, ".")))
		if canonical, ok := extAliases[t]; ok && canonical == f.Name {
			return true
		}
	}
	return false
}

// Image is a validated, re-encoded image ready to be stored.
type Image struct {
	// Data is the re-encoded content. It is not the bytes that were uploaded.
	Data []byte
	// Filename is generated by the server. The client's filename is discarded
	// entirely: it is attacker-controlled and would otherwise contribute path
	// separators, null bytes, a second extension, or enough predictability to help
	// someone enumerate other people's uploads.
	Filename    string
	ContentType string
	Format      string
	Width       int
	Height      int
}

// SanitizeImage validates a multipart upload and returns re-encoded image bytes.
func SanitizeImage(fh *multipart.FileHeader, opts Options) (*Image, error) {
	if fh == nil {
		return nil, ErrEmptyFile
	}
	if opts.MaxBytes > 0 && fh.Size > opts.MaxBytes {
		return nil, fmt.Errorf("%w: %d bytes exceeds the %d byte limit", ErrTooLarge, fh.Size, opts.MaxBytes)
	}

	f, err := fh.Open()
	if err != nil {
		return nil, fmt.Errorf("open upload: %w", err)
	}
	defer f.Close()

	// Read through a limit reader rather than trusting fh.Size, which comes from the
	// multipart headers and is not authoritative.
	var reader io.Reader = f
	if opts.MaxBytes > 0 {
		reader = io.LimitReader(f, opts.MaxBytes+1)
	}

	data, err := io.ReadAll(reader)
	if err != nil {
		return nil, fmt.Errorf("read upload: %w", err)
	}
	if len(data) == 0 {
		return nil, ErrEmptyFile
	}
	if opts.MaxBytes > 0 && int64(len(data)) > opts.MaxBytes {
		return nil, fmt.Errorf("%w: exceeds the %d byte limit", ErrTooLarge, opts.MaxBytes)
	}

	return SanitizeImageBytes(data, opts)
}

// SanitizeImageBytes performs validation on raw bytes. Split out from
// SanitizeImage so the security behaviour can be tested without constructing
// multipart requests.
func SanitizeImageBytes(data []byte, opts Options) (*Image, error) {
	if len(data) == 0 {
		return nil, ErrEmptyFile
	}
	if opts.MaxBytes > 0 && int64(len(data)) > opts.MaxBytes {
		return nil, fmt.Errorf("%w: exceeds the %d byte limit", ErrTooLarge, opts.MaxBytes)
	}

	// DecodeConfig reads only the header, so dimensions can be checked before
	// committing memory to a full decode.
	cfg, formatName, err := image.DecodeConfig(bytes.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrNotAnImage, err)
	}

	format, supported := supportedFormats[formatName]
	if !supported {
		return nil, fmt.Errorf("%w: %s", ErrFormatBlocked, formatName)
	}
	if !opts.allows(format) {
		return nil, fmt.Errorf("%w: %s is not in the configured allowed types", ErrFormatBlocked, format.Ext)
	}
	if cfg.Width <= 0 || cfg.Height <= 0 {
		return nil, ErrNotAnImage
	}
	if int64(cfg.Width)*int64(cfg.Height) > maxPixels {
		return nil, fmt.Errorf("%w: %dx%d", ErrTooManyPixels, cfg.Width, cfg.Height)
	}

	encoded, width, height, err := decodeAndReencode(data, format)
	if err != nil {
		return nil, err
	}

	return &Image{
		Data:        encoded,
		Filename:    uuid.NewString() + "." + format.Ext,
		ContentType: format.ContentType,
		Format:      format.Name,
		Width:       width,
		Height:      height,
	}, nil
}

// decodeAndReencode rebuilds the file from decoded pixel data, discarding
// everything that is not image content: appended archives, trailing HTML, EXIF
// payloads and any bytes a parser might otherwise reach.
func decodeAndReencode(data []byte, format Format) ([]byte, int, int, error) {
	var out bytes.Buffer

	switch format.Name {
	case "gif":
		// DecodeAll/EncodeAll preserves animation; image.Decode would silently
		// flatten a multi-frame GIF to its first frame.
		g, err := gif.DecodeAll(bytes.NewReader(data))
		if err != nil {
			return nil, 0, 0, fmt.Errorf("%w: %v", ErrNotAnImage, err)
		}
		if len(g.Image) == 0 {
			return nil, 0, 0, ErrNotAnImage
		}
		if err := gif.EncodeAll(&out, g); err != nil {
			return nil, 0, 0, fmt.Errorf("re-encode gif: %w", err)
		}
		return out.Bytes(), g.Config.Width, g.Config.Height, nil

	case "png":
		img, err := png.Decode(bytes.NewReader(data))
		if err != nil {
			return nil, 0, 0, fmt.Errorf("%w: %v", ErrNotAnImage, err)
		}
		encoder := png.Encoder{CompressionLevel: png.DefaultCompression}
		if err := encoder.Encode(&out, img); err != nil {
			return nil, 0, 0, fmt.Errorf("re-encode png: %w", err)
		}
		b := img.Bounds()
		return out.Bytes(), b.Dx(), b.Dy(), nil

	case "jpeg":
		img, err := jpeg.Decode(bytes.NewReader(data))
		if err != nil {
			return nil, 0, 0, fmt.Errorf("%w: %v", ErrNotAnImage, err)
		}
		if err := jpeg.Encode(&out, img, &jpeg.Options{Quality: 88}); err != nil {
			return nil, 0, 0, fmt.Errorf("re-encode jpeg: %w", err)
		}
		b := img.Bounds()
		return out.Bytes(), b.Dx(), b.Dy(), nil
	}

	return nil, 0, 0, fmt.Errorf("%w: %s", ErrFormatBlocked, format.Name)
}

// ContentTypeForExt returns the Content-Type an already-stored file should be
// served with, and whether the extension is one this package produces. Serving
// code uses it instead of inferring a type from the filename, so a file that
// predates this validation can never be served as text/html.
func ContentTypeForExt(ext string) (string, bool) {
	ext = strings.ToLower(strings.TrimPrefix(ext, "."))
	canonical, ok := extAliases[ext]
	if !ok {
		return "", false
	}
	format, ok := supportedFormats[canonical]
	if !ok {
		return "", false
	}
	return format.ContentType, true
}
